version: '3.7'
networks:
    office:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: 192.168.229.0/28

volumes:
    postgres:
    redis:

services:
    db:
        container_name: office_db
        image: postgres:12.3
        volumes:
            - postgres:/var/lib/postgresql/data
            - ./docker/postgres/:/docker-entrypoint-initdb.d
        restart: on-failure
        ports:
            - ${DB_PORTS}
        environment:
            POSTGRES_MULTIPLE_DATABASES: "skeleton_test:skeleton_test"
            POSTGRES_DB: skeleton
            POSTGRES_USER: skeleton
            POSTGRES_PASSWORD: skeleton
        networks:
            - office
    nginx:
        image: nginx:1.19.0
        restart: on-failure
        volumes:
            - './api/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - ${NGINX_PORTS}
        depends_on:
            - php
        networks:
            - office
        container_name: office_nginx
    php:
        hostname: "socket-php"
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        restart: on-failure
        networks:
            - office
        container_name: office_backend
        volumes:
            - ./api/:/usr/src/app
            - ./docs/swagger:/usr/src/docs
            - ./docker/php/supervisor/:/usr/src/supervisor
        environment:
            PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
            DOMAIN: ${DOMAIN}