parameters:
    - { resource: parameters.yaml }
services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    WebOffice\Domain\:
        resource: '../src/Domain/*'

    WebOffice\App\:
        resource: '../src/App/*'


    WebOffice\App\Controller\:
        resource: '../src/App/Controller/'
        tags: ['controller.service_arguments']
