imports:
    - { resource: parameters.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Bunker\Application\:
        resource: '../src/Application/*'
        exclude:
            - '../src/Application/Entity/*'

    Bunker\Domain\:
        resource: '../src/Domain/*'

    Bunker\Application\Controller\:
        resource: '../src/Application/Controller'
        tags: ['controller.service_arguments']

